### ISSUE TITLE
Question: what's `deploy_cfg` in `python3 onnx2tensorrt.py`?

### ISSUE THREAD

**Issue by fei4xu** [Yibin122/TensorRT-SMOKE#2]
HI

I'm trying to run the 3rd step:
> #3.Generate engine
python onnx_to_tensorrt.py  # smoke.trt8

it seems that I need to pass 3 parameters to it because of the error message:
```sh
f@nano:~/github/mmdeploy/tools$ python3 onnx2tensorrt.py ../../mmdetection3d/smoke.onnx smoke.trt
usage: onnx2tensorrt.py [-h] [--device-id DEVICE_ID] [--calib-file CALIB_FILE]
                        [--log-level {CRITICAL,FATAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}]
                        deploy_cfg onnx_path output
```

what's the value of `deploy_cfg` should I pass?

(I'm brand new to all these....... machine learning world....)

**Comment by fei4xu** [comment]
I figured it out, I should run like:
```sh
python3 onnx2tensorrt.py ../../mmdeploy/configs/mmdet/detection/detection_tensorrt-fp16_dynamic-320x320-1344x1344.py ../../mmdetection3d/smoke.onnx smoke.trt
```

**Comment by Yibin122** [comment]
For the 3rd step you can use TensorRT API as well:
`./trtexec --workspace=4096 --onnx=${model_path}/smoke.onnx --saveEngine=${model_path}/smoke.engine`

I have updated README and MMDeploy is not required anymore.
